name: drift_me
description: Studying the use of drift local database


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  drift: ^2.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.11
  path: ^1.8.2

  get: ^4.6.5
  dropdown_formfield: ^0.1.4

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.5.2
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
